---
# Play 1: Create EC2 Instance
- name: Deploy EC2 Instance 
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    
    instance_type: t2.nano
    image: ami-0dee22c13ea7a9a67  # Ubuntu AMI
    key_name: ec2instance-keys  # Update this with your key pair name
  

  tasks:

     - name: Launch EC2 Instance
       amazon.aws.ec2_instance:
        name: "Ansible_Nginx"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        wait: yes
        state: running
        tags:
          Env: "Ansible_Nginx_Server"
        network:
           assign_public_ip: true
       register: ec2_instance

     - name: Wait for SSH to come up
       wait_for:
        host: "{{ ec2_instance.instances[0].public_ip_address }}"
        port: 22
        delay: 60
        timeout: 300

     - name: Add new EC2 instance to host group
       add_host:
        hostname: "{{ ec2_instance.instances[0].public_ip_address }}"
        groupname: launched

     - name: Wait for SSH
       wait_for_connection:
        delay: 10
       delegate_to: "{{ ec2_instance.instances[0].public_ip_address }}"

# Play 2: Install Nginx on the Server and Start it 
- name: Install and Configure Nginx
  hosts: launched
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    
    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes